### ISSUE TITLE
Screenshots are not included on the json report

### ISSUE THREAD

**Issue by guilhotarras** [Andras-Marozsi/cucumber-parallelly#4]
When scenario takes a screenshot, its not included on the json report file, and is not shown on the html file, after its generation.
In my case, I have this code on the hooks file: 

this.After({tags: ['@01_web_app_build_number']}, function(scenario) {
        this.browser.takeScreenshot()
            .then( buffer => scenario.attach(new Buffer(buffer, 'base64'), 'image/png') )
    });

**Comment by andras-marozsi** [comment]
Hey there,

This should work, but `browser.takeScreenshot()` function is asynchronous. Can you give this a try:
```
this.After({tags: ['@01_web_app_build_number']}, function(scenario) {
  return this.browser.takeScreenshot()
    .then( buffer => scenario.attach(new Buffer(buffer, 'base64'), 'image/png') )
});
```

Also, in my tests I use the following:
```
scenario.attach(new Buffer(buffer, 'base64').toString('binary'), 'image/png');
```
I'm not quite sure why I had to introduce this (was a long time ago), just wanted to give you a hint if you find any more issues.

Let me know if this helped!
